### ISSUE TITLE
Asking for experimental data 

### ISSUE THREAD

**Issue by leizan** [ylincen/CMI-adaptive-hist#1]
Hello, your paper is really promising, bravo! And could you share the result of other methods(e.g. MS, FP, RAVK) in experiments I-V?

**Comment by ylincen** [comment]
Hi, thanks for the message. For MS, FP, RAVK we use the code from https://github.com/leizan/knncmi. And for JIC, we use the R package BNSL; for RCIT/RCoT, R package RCIT; for MIIC; R package miic. Hope this helps, and please do not hesitate to contact us if we could further help.

**Comment by leizan** [comment]
Thank you for your replying, it's helpful.

**Comment by leizan** [comment]
Hi, I have another question about the graph on the bottom-right of Figure 1 in your paper, why the MIIC terminates at 500?

**Comment by ylincen** [comment]
MIIC performs super well there and the error is (almost) 0. In this plot, the y-axis is transformed by the log function so it is not possible to draw it (as it becomes minus infinity).

**Comment by leizan** [comment]
OK. Thanks for your reply.
